### PR TITLE
Added support for new-style modules

### PR DESCRIPTION
**Pull request by Endle**

### CODE REVIEW

**Comment by Endle** [comment]
@Jazzinghen as mentioned, I cherry-picked your other changes in https://github.com/Endle/rust-bundler-cp/pull/26 , leaving the core changes for review.

I plan to add a bit test cases to Expander, and add some docs about this change. After that, I would merge this PR to truck.

**Comment by Jazzinghen** [comment]
Oh, man. I am sorry, I forgot to reply to your comment.
That seems like a good plan. If you'd like me to help with something let me know!

**Comment by Endle** [comment]
@Jazzinghen Could you please review this PR?


> I plan to add a bit test cases to Expander, and add some docs about this change

I still have this on my todo list. However, I found my code needs more improvement than I expected. I don't think blocking this PR too long is a good idea.

In short, if you think the current change looks good to you, I'll merge it into master.

**Comment by Jazzinghen** [comment]
I just saw all the PRs! This is way better than my single PR, haha
Seems fine to me

**Comment by Endle** [comment]
@Jazzinghen Could you please test 0.3.15?  (It will be pushed to cargo automatically later)

Besides, (if not confidential/sensitive), could you add your competitive computing template as a test case? It could avoid my unintentional breaking changes.

**Comment by Jazzinghen** [comment]
No problem in testing/adding my template as a test, it's nothing great, haha.
Nice job with the PR @Endle !

**Pull request merged**
